CREATE PROCEDURE UPDATEINVOICE(
    IN p_ID VARCHAR(30),
    IN p_INFRASTRUCTURE_ID VARCHAR(100),
    IN p_PRICE DECIMAL(65, 2),
    IN p_WATER_PRICE DECIMAL(65, 2),
    IN p_ELECTRICITY_PRICE DECIMAL(65, 2),
    IN p_OLD_ELECTRICITY_NUMBER BIGINT,
    IN p_NEW_ELECTRICITY_NUMBER BIGINT,
    IN p_OLD_WATER_NUMBER BIGINT,
    IN p_NEW_WATER_NUMBER BIGINT,
    IN p_TOTAL_PRICE DECIMAL(65, 2)
)
BEGIN
  UPDATE INVOICES
    SET
    INFRASTRUCTURE_ID = p_INFRASTRUCTURE_ID,
    PRICE = p_PRICE,
    WATER_PRICE = p_WATER_PRICE,
    ELECTRICITY_PRICE = p_ELECTRICITY_PRICE,
    OLD_ELECTRICITY_NUMBER = p_OLD_ELECTRICITY_NUMBER,
    NEW_ELECTRICITY_NUMBER = p_NEW_ELECTRICITY_NUMBER,
    OLD_WATER_NUMBER = p_OLD_WATER_NUMBER,
    NEW_WATER_NUMBER = p_NEW_WATER_NUMBER,
    TOTAL_PRICE = p_TOTAL_PRICE
    WHERE ID = p_ID;
END;
