CREATE PROCEDURE CREATEINVOICE(
    IN ID VARCHAR(30),
    IN INFRASTRUCTURE_ID VARCHAR(100),
    IN PRICE DECIMAL(65, 2),
    IN WATER_PRICE DECIMAL(65, 2),
    IN ELECTRIC_PRICE DECIMAL(65, 2),
    IN OLD_ELECTRIC_NUMBER BIGINT(10),
    IN NEW_ELECTRIC_NUMBER BIGINT(10),
    IN OLD_WATER_NUMBER BIGINT(10),
    IN NEW_WATER_NUMBER BIGINT(10),
    IN TOTAL_PRICE DECIMAL(65, 2)
)
BEGIN
    INSERT INTO INVOICES(
        ID,
        INFRASTRUCTURE_ID,
        PRICE,
        WATER_PRICE,
        ELECTRICITY_PRICE,
        OLD_ELECTRICITY_NUMBER,
        NEW_ELECTRICITY_NUMBER,
        OLD_WATER_NUMBER,
        NEW_WATER_NUMBER,
        TOTAL_PRICE) 
        VALUES (
        ID,
        INFRASTRUCTURE_ID,
        PRICE,
        WATER_PRICE,
        ELECTRIC_PRICE,
        OLD_ELECTRIC_NUMBER,
        NEW_ELECTRIC_NUMBER,
        OLD_WATER_NUMBER,
        NEW_WATER_NUMBER,
        TOTAL_PRICE
    );
END;