CREATE PROCEDURE INSERTNOTICE(
    IN P_TITLE VARCHAR(100),
    IN P_AMOUNT_RECEIVED DECIMAL(65, 2),
    IN P_REMAINING_AMOUNT DECIMAL(65, 2),
    IN P_INVOICE_ID VARCHAR(100),
    IN P_DESCRIPTION VARCHAR(255)
)
BEGIN
    INSERT INTO NOTICES(TITLE, AMOUNT_RECEIVED, REMAINING_AMOUNT, INVOICE_ID, DESCRIPTION)
    VALUES (P_TITLE, P_AMOUNT_RECEIVED, P_REMAINING_AMOUNT, P_INVOICE_ID, P_DESCRIPTION);
END;